# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Calculadora_De_Coordenadas
                                 A QGIS plugin
 Convierte las coordenadas DMS a DD o viceversa
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-05-06
        copyright            : (C) 2023 by Kathia Pineda
        email                : leonelap707@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Calculadora_De_Coordenadas class from file Calculadora_De_Coordenadas.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Calculadora_De_Coordenadas import Calculadora_De_Coordenadas
    return Calculadora_De_Coordenadas(iface)
