# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Calculadora_De_Coordenadas
                                 A QGIS plugin
 Convierte las coordenadas DMS a DD o viceversa
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-05-06
        git sha              : $Format:%H$
        copyright            : (C) 2023 by Kathia Pineda
        email                : leonelap707@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog

from .Calculadora_De_Coordenadas_dialog import Calculadora_De_CoordenadasDialog
#from qgis.core import QgsProject
#from PyQt5.QtGui import QIcon, QFileDialog
#import processing
#from qgis.utils import iface
import os.path

class Calculadora_De_Coordenadas:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'Calculadora_De_Coordenadas_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Calculadora De Coordenadas')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('Calculadora_De_Coordenadas', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/Calculadora_De_Coordenadas/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u''),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Calculadora De Coordenadas'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = Calculadora_De_CoordenadasDialog()

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            ################################################################
            def DMS(self):
                G1 = int(self.GradosLat.text())
                M1 = int(self.MinLat.text())
                S1 = float(self.SegLat.text())
                G2 = int(self.GradosLon.text())
                M2 = int(self.MinLon.text())
                S2 = float(self.SegLon.text())
                if(G1<0):
                    X="° S, "
                else:
                    X="° N, "
                if(G2<0):
                    Y="° W"
                else:
                    Y="° E"
                DD1 = round(G1+int(M1)/60+float(S1)/3600,1)
                DD2 = round(G2+int(M2)/60+float(S2)/3600,1)
                DD3 = str(DD1) + X +  str(DD2) + Y 
                self.ResultadoDD.setText(DD3)

            ###########################################################
            def DD(self):
            
                Latitud  = float(self.Latitud.text())
                Longitud = float(self.Longitud.text()) 
                G1 = int(Latitud)
                G2 = int(Longitud)
                M1 = int((Latitud-G1)*60)
                M2 = int((Longitud-G2)*60) 
                S1 = round(float((((Latitud-G1)*60)-M1)*60),1)
                S2 = round(float((((Longitud-G2)*60)-M2)*60),1)
                if(G1<0):
                    X = "S, "
                else:
                    X = "N, "
                if(G2<0):
                    Y = "W"
                else:
                    Y = "E"
                self.ResultadoDMS.setText(str(G1)+"° "+str(M1)+"\' "+str(S1)+"\'' " + X + str(G2)+"° "+str(M2)+"\' "+str(S2)+"\'' " + Y)
            self.DMSaDD.clicked.connect(DD)
            self.DDaDMS.clicked.connect(DMS)